twig:
    file_name_pattern: '*.twig'
    globals:
        app_name: '%env(APP_NAME)%'
        app_tagline: '%env(APP_TAGLINE)%'
        app_whoami: '%env(APP_WHOAMI)%'
        app_mailto: '%env(APP_MAILTO)%'
        app_tel: '%env(APP_TEL)%'

when@test:
    twig:
        strict_variables: true
